### ISSUE TITLE
Error Compiling lib/module.ex

### ISSUE THREAD

**Issue by maatthc** [erlyvideo/erlyvideo-old#2]
Guys,
I'm getting this error with the latest version of Erlyvideo from Github:

==> erlyvideo (compile)
==> elixir (compile)
make[1]: Entrando no diretório `/win/erlyvideo/apps/elixir'
Compiling Elixir source ...
erl -I include -noshell -pa ebin -s elixir_compiler core -s erlang halt
Compiling lib/module.ex
{"init terminating in do_boot",{{badmatch,{error,einval}},[{elixir_compiler,binary_to_path,2},{lists,foreach,2},{elixir_compiler,'-core/0-lc$^0/1-0-',1},{elixir_compiler,core,0},{init,start_it,1},{init,start_em,1}]}}

Crash dump was written to: erl_crash.dump
init terminating in do_boot ()
make[1]: *\* [exbin] Erro 1
make[1]: Saindo do diretório `/win/erlyvideo/apps/elixir'
ERROR: Command [compile] failed!
make: *\* [compile] Erro 1

---

I'm using Ubuntu 11.10 with Erlang R14B02 (erts-5.8.3) and :
root@casabh:/win/erlyvideo# uname -a
Linux casabh 3.0.0-13-generic #22-Ubuntu SMP Wed Nov 2 13:25:36 UTC 2011 i686 athlon i386 GNU/Linux

**Comment by maxlapshin** [comment]
Update to latest erlang.

**Comment by maatthc** [comment]
Tks maxlapshin!
I pulled the last version of Erlyvideo from Git yesterday and even with the same version of Erlang I could compile it.
